### PR TITLE
[mellanox] Add D32C12S2 SKU to 4600C

### PR DESCRIPTION
**Pull request by alexrallen**
#### Why I did it

New SKU by customer request. 

```
4  100G Downlinks
2  10G  Downlinks
32 50G  Downlinks
8  100G Uplinks
```

#### How I did it

Duplicated existing 4600C SKU and updated
- Port Speeds
- Buffer Default Values
- Default Breakout Modes
- SAI Profile Speeds & Breakout Capabilities

#### How to verify it

Tested on 4600C with hardware loopback connections. 

#### Which release branch to backport (provide reason below if selected)

For the purposes of internal review this is based against master. A PR will be submitted individually against 202012 and 202106 / master 

#### Description for the changelog
[mellanox] Add D32C12S2 SKU to 4600C

#### A picture of a cute animal (not mandatory but encouraged)
alpaca-1

### CODE REVIEW

**Comment by vivekreddynv** [comment]
@alexrallen, Can you add the number of uplinks & downlinks requested?. It'll assist in reviewing the buffer values

**Comment by alexrallen** [comment]
> 
> 
> @alexrallen, Can you add the number of uplinks & downlinks requested?. It'll assist in reviewing the buffer values

Revised, thanks.

**Comment by dgsudharsan** [comment]
@alexrallen  This SKU is supposed to be similar to D100C12S2 SKU of S3800. The 50G ports are 2x50 instead of just 50G. Can you please update?

**Comment by dgsudharsan** [comment]
This is the reference SKU https://github.com/Azure/sonic-buildimage/blob/master/device/mellanox/x86_64-mlnx_msn3800-r0/Mellanox-SN3800-D100C12S2/port_config.ini

**Pull request closed without merging**
